# -*- coding: utf-8 -*-
# Inhoud van decorateursgids.be: tien thema's, elk met een artikel en een verwijzing.

SITE = {
    "domain": "decorateursgids.be",
    "url": "https://decorateursgids.be",
    "name": "Decorateursgids",
    "tagline": "Gids voor wie een ruimte afwerkt",
    "description": "Praktische gids over het afwerken en aankleden van een woning: verf, vloeren, raamdecoratie, meubels, woonaccessoires en het ophangen ervan.",
    "email": "info@decorateursgids.be",
}

THEMES = [
    {
        "slug": "woonaccessoires",
        "nr": "01",
        "title": "Woonaccessoires",
        "h1": "Woonaccessoires: de laatste laag van een interieur",
        "meta": "Hoe woonaccessoires een afgewerkte ruimte tot een bewoonde ruimte maken. Over kussens, tapijten, servies, textiel en het kiezen van een samenhangend geheel.",
        "intro": "Een decorateur levert een ruimte af met geschilderde muren, een gelegde vloer en gordijnen die hangen. Toch oogt zo'n ruimte pas af wanneer de laatste laag erop ligt: het textiel, het servies op de kast, de mand naast de zetel, het tapijt onder de tafel. Die laag heet in de vakwereld de styling en ze bepaalt meer van de sfeer dan menigeen vermoedt.",
        "kort": [
            "Kies eerst een kleurenpalet van drie tinten en houd daar bij elke aankoop aan vast.",
            "Werk in lagen: groot textiel eerst, daarna middelgrote stukken, pas als laatste de kleine voorwerpen.",
            "Een tapijt bepaalt de zone; te klein gekozen tapijten zijn de meest gemaakte fout.",
            "Beter drie goede stukken dan vijftien losse spullen.",
        ],
        "sections": [
            ("Waarom de laatste laag zo zwaar weegt",
             ["Muren, vloer en plafond vormen samen het grootste oppervlak van een kamer, maar het oog blijft niet aan vlakken hangen. Het oog zoekt contrast, textuur en herhaling. Een linnen kussen op een wollen zetel, een keramische schaal op een eiken tafel, een katoenen plaid over een leren stoel: precies daar ontstaat het gevoel dat iemand hier woont.",
              "Decorateurs noemen dit de gelaagdheid van een interieur. Elke laag voegt een materiaal, een tint of een structuur toe. Een ruimte zonder die lagen voelt als een toonzaal. Een ruimte met te veel lagen voelt als een rommelmarkt. De kunst zit in het midden."]),
            ("Beginnen bij het palet",
             ["Wie woonaccessoires koopt zonder plan, komt thuis met een verzameling die niet bij elkaar past. Een eenvoudig hulpmiddel is een palet van drie tinten: een basistint die de grote vlakken volgt, een tweede tint die daar rustig naast staat en een accenttint die maar op enkele plekken terugkomt.",
              "Een woonkamer met zandkleurige muren en een eiken vloer krijgt bijvoorbeeld gebroken wit als basis, olijfgroen als tweede tint en roestbruin als accent. Kussens in olijf, een plaid in roest, een vaas in gebroken wit. Alles wat buiten dat palet valt, blijft in de winkel. Dat klinkt streng, maar het is de reden waarom ingerichte huizen in tijdschriften zo rustig ogen."]),
            ("Groot naar klein",
             ["De volgorde van aankopen doet ertoe. Eerst het tapijt, want dat bepaalt de zone en de kleurtoon van de hele hoek. Daarna de gordijnen, de grootste textielvlakken in de kamer. Vervolgens de kussens en plaids op zitmeubelen. Pas dan komen de kleine voorwerpen: kandelaars, schalen, kaders, boeken.",
              "Wie andersom werkt, koopt een prachtige schaal en zoekt daar een tapijt bij. Dat lukt zelden. Het tapijt is duurder, groter en bepalender, dus het tapijt komt eerst.",
              "Over dat tapijt: een klassieke fout is een te klein exemplaar dat als een eiland midden in de kamer ligt. Een tapijt onder een zithoek hoort minstens onder de voorpoten van alle zitmeubelen te liggen. Onder een eettafel hoort het tapijt zo groot te zijn dat een achteruitgeschoven stoel er nog op staat."]),
            ("Tafel en keuken tellen mee",
             ["Woonaccessoires beperken zich niet tot de woonkamer. Servies, glaswerk, placemats en een bestekset zijn evengoed decoratie, zeker in een woning met een open keuken waar de tafel het middelpunt is. Een stapel borden in een rustige tint op een open rek werkt als een stilleven. Hetzelfde geldt voor voorraadpotten, een broodplank of een mooie waterkan.",
              "In de badkamer en slaapkamer geldt dezelfde logica. Handdoeken in een tint uit het palet, een dekbedovertrek dat aansluit bij de gordijnen, een badmat die niet vloekt met de tegels. Kleine keuzes, groot effect."]),
            ("Waar decorateurs hun accessoires halen",
             ["Voor de laatste laag van een interieur kijken veel decorateurs in Vlaanderen naar Salins Home, een winkel in Heusden-Zolder met een webshop op https://salinshome.be/. Het aanbod loopt van tafel en keuken tot badkamer, slaapkamer en decoratie, met merken als PIP Studio, Heritage en Karaca. Handig aan zo'n breed aanbod is dat een volledig palet bij een leverancier te vinden is, van servies tot kussens, waardoor de tinten op elkaar afgestemd blijven."]),
        ],
        "partner": {"name": "Salins Home", "url": "https://salinshome.be/", "anchor": "Salins Home",
                    "blurb": "Woonaccessoires en interieurdecoratie voor tafel, keuken, badkamer, slaapkamer en woonkamer."},
    },
    {
        "slug": "klokken",
        "nr": "02",
        "title": "Klokken",
        "h1": "Een klok kiezen die bij de ruimte past",
        "meta": "Wandklokken, tafelklokken en staande klokken als onderdeel van de inrichting. Over formaat, plaats, stijl en het ophangen van een klok.",
        "intro": "Een klok is een van de weinige voorwerpen die tegelijk decoratie en gebruiksvoorwerp is. Iedereen kijkt er meerdere keren per dag naar, en daarom hoort een klok op een plek en in een formaat dat klopt met de kamer. Een te kleine klok op een grote muur verdwijnt, een te grote klok in een smalle gang drukt.",
        "kort": [
            "Meet de muur en kies de diameter naar het vlak: ongeveer een derde van de breedte van een leeg muurdeel is een goede vuistregel.",
            "Hang een wandklok op ooghoogte, rond 150 tot 160 centimeter tot het midden van de wijzerplaat.",
            "Kies een uurwerk met stil loopwerk voor slaapkamer en bureau.",
            "Een klok boven de zetel of het buffet werkt als anker voor een muur die verder leeg blijft.",
        ],
        "sections": [
            ("Formaat en verhouding",
             ["De meest gemaakte fout is een klok die te klein is voor het vlak waar hij hangt. Een muur van drie meter breed met een klok van dertig centimeter erop lijkt onbewoond. Een vuistregel uit de decoratiepraktijk: neem een derde tot de helft van de breedte van het lege muurdeel als diameter. Boven een dressoir van 180 centimeter mag een klok dus gerust zestig tot tachtig centimeter meten.",
              "In een kleinere ruimte, zoals een gang of een toilet, draait het om. Daar hoort een klok die niet meer dan een derde van de vrije muurbreedte inneemt, anders wordt de ruimte visueel nog smaller."]),
            ("Hoogte en plaats",
             ["Een wandklok hangt op ooghoogte, met het midden van de wijzerplaat tussen 150 en 160 centimeter van de vloer. Hangt er een meubel onder, dan zit de onderrand van de klok best 15 tot 25 centimeter boven het meubel, zodat klok en meubel als een geheel lezen.",
              "De klassieke plekken zijn de muur tegenover de ingang van de kamer, de muur boven een buffet of dressoir en de wand in de keuken waar de ogen vanzelf naartoe gaan tijdens het koken. In een slaapkamer past een kleine tafelklok op het nachtkastje beter dan een wandklok die de hele nacht tikt."]),
            ("Stijl afstemmen op het interieur",
             ["Een klok hoeft niet in dezelfde stijl te zijn als de rest van de kamer, maar hij mag er ook niet mee vloeken. In een strak interieur werkt een klok met een rustige wijzerplaat, dunne wijzers en een metalen of houten rand. In een landelijk interieur past een stationsklok, een klok met Romeinse cijfers of een houten exemplaar. In een industrieel interieur mogen tandwielen zichtbaar zijn en mag de klok groot en zwaar ogen.",
              "Wie twijfelt, kiest een klok in een tint die al in de kamer voorkomt. Een zwarte klok in een kamer met zwarte lampen en zwarte kaders lijkt er altijd bij te horen."]),
            ("Loopwerk en geluid",
             ["Een detail dat vaak vergeten wordt: het geluid. Een klassiek kwartsuurwerk tikt hoorbaar, wat in een woonkamer sfeervol kan zijn maar in een slaapkamer of op een bureau stoort. Er bestaan uurwerken met een zogenaamd sweep-loopwerk, waarbij de secondewijzer vloeiend beweegt en de klok nagenoeg stil is. Voor slaapkamer, bureau en leeshoek is dat de betere keuze.",
              "Staande klokken en pendules met een slagwerk vragen om een plek waar het slaan niet stoort, en om een stabiele, vlakke ondergrond. Een pendule op een schuine vloer loopt niet goed."]),
            ("Ophangen",
             ["Een klok tot ongeveer twee kilo hangt aan een schroef met plug in een gemetselde muur. Zwaardere klokken vragen een tweede bevestigingspunt of een speciale ophangbeugel. In een gipskartonwand is een hollewandplug nodig. Meer over het juiste boortje per wandtype staat in het thema over boren en ophangen op deze site."]),
            ("Aanbod in België",
             ["Wie in België een klok zoekt, komt al snel uit bij https://www.klokken.be/, een webshop met een ruim aanbod van meer dan duizend klokken, waaronder een grote collectie wandklokken op https://www.klokken.be/wandklok/. Het assortiment loopt van strakke moderne klokken tot klassieke stationsklokken en tafelklokken, wat het eenvoudig maakt om per interieurstijl te vergelijken."]),
        ],
        "partner": {"name": "Klokken.be", "url": "https://www.klokken.be/", "anchor": "https://www.klokken.be/",
                    "blurb": "Wandklokken, tafelklokken en staande klokken in alle stijlen, ruim aanbod uit voorraad."},
    },
    {
        "slug": "boren-en-ophangen",
        "nr": "03",
        "title": "Boren en ophangen",
        "h1": "Boren en ophangen: het juiste boortje per muur",
        "meta": "Kaders, klokken, gordijnrails en rekken ophangen zonder schade. Welke boor bij welke muur, welke plug bij welk gewicht en hoe een decorateur netjes werkt.",
        "intro": "Alles wat een decorateur aan een muur hangt, van een kader tot een gordijnrail, begint met een gat. Het verschil tussen een strak resultaat en een muur vol uitgebrokkelde gaten zit in drie keuzes: het juiste boortje, de juiste plug en de juiste snelheid. Dit artikel zet die keuzes op een rij.",
        "kort": [
            "Baksteen en beton: steenboor met hardmetalen punt, klopstand aan. Gipskarton: gewone boor zonder klopstand.",
            "Hout: houtboor met centreerpunt. Metaal: HSS-metaalboor, langzaam toerental, licht smeren.",
            "Kies de plugdiameter gelijk aan de boordiameter; de schroef is een maat kleiner dan de plug.",
            "Plak een stukje schilderstape op de muur voor een schone boorplek zonder uitbrokkelen.",
        ],
        "sections": [
            ("Eerst weten waarin geboord wordt",
             ["Een Belgische woning kan uit heel verschillende wanden bestaan. Buitenmuren en oudere binnenmuren zijn meestal baksteen. Nieuwbouw heeft vaak snelbouwsteen of cellenbeton, en scheidingswanden zijn geregeld gipskarton op een houten of metalen frame. Vloerplaten en kolommen zijn beton. Elk materiaal vraagt een ander boortje.",
              "Een handige test: klop met de knokkels op de muur. Een holle klank betekent gipskarton of een voorzetwand. Een doffe, harde klank wijst op steen of beton. Daarnaast is het verstandig om met een leidingzoeker te controleren waar elektriciteit en water lopen, zeker naast schakelaars en stopcontacten en boven de keukenaanrecht."]),
            ("Steen en beton",
             ["Voor baksteen en beton is een steenboor nodig, herkenbaar aan de brede hardmetalen punt. In baksteen volstaat een gewone klopboormachine met de klopstand aan. In beton en zeker in oudere, harde beton werkt een boorhamer met SDS-opname sneller en netter. Boor eerst zonder klopstand een paar millimeter diep, zodat het boortje niet wegloopt, en zet dan de klopstand aan.",
              "Cellenbeton en snelbouwsteen zijn zacht en poreus. Daar wordt zonder klopstand geboord, anders wordt het gat te ruim en houdt de plug niet. Voor deze materialen bestaan speciale pluggen met brede vleugels."]),
            ("Gipskarton en holle wanden",
             ["In gipskarton wordt met een gewone spiraalboor geboord, zonder klopstand, en met een hollewandplug bevestigd. Voor lichte voorwerpen zoals een kader volstaat een kunststof hollewandplug. Voor zwaardere dingen zoals een gordijnrail, een klok van enkele kilo's of een wandrek is een metalen hollewandanker of een kantelplug nodig. Nog beter is het om de houten of metalen staander achter de plaat te vinden en daarin te schroeven; een magneetje verraadt de schroeven van de plaat en dus de plaats van de staander."]),
            ("Hout en metaal",
             ["In hout, bijvoorbeeld een houten lambrisering of een balk, wordt met een houtboor geboord. Die heeft een fijne centreerpunt zodat het gat precies op de markering blijft. In metaal, denk aan een stalen profiel of een metalen gordijnrail die op maat wordt geboord, hoort een HSS-metaalboor. Metaal wordt geboord op een laag toerental, met een druppel olie, en na een eerste klein voorboorgat voor grotere diameters.",
              "Een goede set metaalboren en houtboren in de gangbare diameters bespaart veel geknoei. Een boortje dat bot is, brandt eerder dan het snijdt; wie rook ziet, stopt en vervangt het boortje."]),
            ("Schoon werken",
             ["Decorateurs werken netjes. Een stukje schilderstape op de boorplek voorkomt dat het pleisterwerk rond het gat uitbrokkelt en dat het boortje wegglijdt. Een stofzuigermond of een gevouwen enveloppe onder het gat vangt het boorstof op. Bij het ophangen van meerdere kaders wordt eerst een sjabloon van papier op de muur geplakt, zodat alle gaten in een keer juist zitten.",
              "Een plug hoort strak in het gat te zitten en volledig weg te zakken in de muur. Steekt de plug uit, dan is het gat te ondiep of te smal. De schroef is een maat kleiner dan de plug: een plug van 6 millimeter krijgt een schroef van 4 tot 5 millimeter."]),
            ("Boortjes kopen",
             ["Wie regelmatig ophangt, heeft baat bij losse boren in de juiste maat in plaats van een goedgevulde maar middelmatige set. In België is https://www.boorkopen.be/ een gespecialiseerde webshop voor metaalboren, houtboren, kernboren en toebehoren, gesorteerd op diameter en uit voorraad leverbaar. Ook batterijen voor meetapparatuur en laserwaterpassen staan er in het aanbod."]),
        ],
        "partner": {"name": "Boorkopen.be", "url": "https://www.boorkopen.be/", "anchor": "https://www.boorkopen.be/",
                    "blurb": "Metaalboren, houtboren, kernboren en toebehoren op diameter, altijd uit voorraad."},
    },
    {
        "slug": "verf-en-kleur",
        "nr": "04",
        "title": "Verf en kleur",
        "h1": "Verf en kleur: een muur kiezen zonder spijt",
        "meta": "Kleur kiezen voor muren en plafond, verfsoorten en glansgraden, en de volgorde van een goed schilderwerk. Voor wie zelf schildert of een decorateur aanstuurt.",
        "intro": "Verf is het middel waarmee een decorateur het meeste verandert met het minste materiaal. Een kamer krijgt met een andere muurkleur een ander karakter, een andere schijnbare grootte en zelfs een ander licht. Precies daarom is de keuze ook zo lastig: een staal van vijf bij vijf centimeter zegt weinig over een muur van vijftien vierkante meter.",
        "kort": [
            "Test kleuren met een proefpot op een vel van minstens een halve meter, en bekijk het op verschillende momenten van de dag.",
            "Noordelijk licht maakt kleuren koeler, zuidelijk licht warmer; kies de tint daarop.",
            "Mat voor muren en plafond, zijdeglans voor houtwerk en vochtige ruimtes.",
            "Volgorde: plafond, muren, houtwerk. Eerst gronden op nieuw pleisterwerk.",
        ],
        "sections": [
            ("Licht bepaalt de kleur",
             ["Dezelfde tint oogt anders in een kamer op het noorden dan in een kamer op het zuiden. Noordelijk licht is koel en blauwachtig; een grijs dat in de winkel warm leek, wordt er kil. Zuidelijk licht is warm en geel; een beige kan er oranje worden. Ook kunstlicht speelt mee: warmwitte lampen trekken kleuren naar geel, koelwitte naar blauw.",
              "De enige betrouwbare methode is een proefvlak. Een proefpot op een groot vel papier, opgehangen op meerdere muren, bekeken 's ochtends, 's middags en 's avonds bij lamplicht. Wie dat overslaat, schildert vaak twee keer."]),
            ("Glansgraad en verfsoort",
             ["Muren en plafonds krijgen in de regel matte muurverf. Mat verbergt kleine oneffenheden en geeft een rustig oppervlak. Voor keuken, badkamer en gang bestaat afwasbare matte verf die tegen een vochtige doek kan. Houtwerk zoals deuren, plinten en kozijnen krijgt lakverf in zijdeglans of hoogglans, omdat die beter reinigbaar is en slagen weerstaat.",
              "Watergedragen lak is tegenwoordig de norm: sneller droog, minder geur en nauwelijks vergeling. Voor buitenhoutwerk en sterk belaste delen wordt nog wel eens voor oplosmiddelhoudende lak gekozen."]),
            ("Voorbereiding is driekwart van het werk",
             ["Een decorateur besteedt meer tijd aan voorbereiden dan aan schilderen. Gaten vullen, schuren, ontvetten, afplakken, afdekken. Nieuw pleisterwerk moet volledig droog zijn en wordt eerst gegrond, anders zuigt de muur de verf ongelijk op en ontstaan vlekken. Oude glanzende lak wordt mat geschuurd voordat er een nieuwe laag op komt.",
              "De volgorde van een kamer is altijd dezelfde: eerst het plafond, dan de muren, dan het houtwerk. Zo vallen spatten van het plafond op muren die nog geschilderd moeten worden, en niet op afgewerkt houtwerk."]),
            ("Kleur en ruimte",
             ["Lichte tinten maken een ruimte groter, donkere tinten maken ze intiemer. Een donker plafond verlaagt een hoge kamer, een lichter plafond dan de muren tilt een lage kamer op. Een kleine kamer wordt niet per se groter door alles wit te schilderen; een middentint op alle muren, inclusief plinten en deuren, laat de grenzen van de ruimte vervagen en werkt vaak beter.",
              "Een accentmuur is een klassiek middel, maar werkt alleen op een muur die iets te vertellen heeft: de wand achter het bed, achter de zetel of rond een schouw. Een willekeurige zijmuur in een andere kleur trekt de aandacht naar een plek waar niets gebeurt."]),
            ("Advies en verf in de winkel",
             ["Een kleurkaart thuis is een begin, maar een gesprek met iemand die dagelijks kleuren afstemt bespaart fouten. Colora, te vinden op https://www.colora.be/, is een Belgische keten van verfwinkels met tientallen vestigingen, verf van het Belgische merk BOSS paints, behang en vinylvloeren. De winkels geven persoonlijk kleuradvies en werken met proefpotten, wat aansluit op de werkwijze uit dit artikel."]),
        ],
        "partner": {"name": "Colora", "url": "https://www.colora.be/", "anchor": "Colora",
                    "blurb": "Verfwinkels met kleuradvies, verf van BOSS paints, behang en vinylvloeren."},
    },
    {
        "slug": "raamdecoratie",
        "nr": "05",
        "title": "Raamdecoratie",
        "h1": "Raamdecoratie: gordijnen, rolgordijnen en lamellen",
        "meta": "Welke raamdecoratie past bij welk raam en welke kamer. Over gordijnen, vitrage, rolgordijnen, jaloezieën en het correct opmeten en ophangen.",
        "intro": "Raamdecoratie doet drie dingen tegelijk: ze regelt licht, ze beschermt de privacy en ze kleedt het raam aan. Een kaal raam maakt een kamer hard en luid; textiel voor het raam dempt geluid en maakt de ruimte zachter. Decorateurs kiezen de raamdecoratie meestal samen met de muurkleur, omdat beide het grootste kleurvlak van de kamer vormen.",
        "kort": [
            "Hang gordijnen zo hoog en zo breed mogelijk: de rail tot tegen het plafond en 20 tot 30 centimeter voorbij het kozijn.",
            "Gordijnen raken de vloer of hangen er een centimeter boven; halfhoge gordijnen ogen onaf.",
            "Slaapkamer: verduisterend. Keuken en badkamer: vochtbestendig, zoals aluminium jaloezieën of kunststof rolgordijnen.",
            "Meet elk raam apart, ook al lijken ze gelijk.",
        ],
        "sections": [
            ("Gordijnen laten een kamer hoger lijken",
             ["De grootste winst bij gordijnen zit in de plaats van de rail. Een rail net boven het kozijn maakt het raam klein. Een rail tot tegen het plafond, of zo hoog mogelijk, trekt de blik omhoog en maakt het raam en de kamer hoger. Breder dan het kozijn hangen zorgt ervoor dat de gordijnen overdag naast het raam vallen en geen licht wegnemen.",
              "Wat de lengte betreft: gordijnen raken de vloer of stoppen een centimeter erboven. In een landelijk interieur mogen ze zelfs een paar centimeter op de vloer breken. Gordijnen die op de vensterbank eindigen, passen alleen bij een raam met een diepe vensterbank en zijn anders een compromis."]),
            ("Per kamer een andere keuze",
             ["In de slaapkamer is verduisterende stof of een verduisterend rolgordijn achter een gewoon gordijn de norm. In de woonkamer volstaat lichte stof of een combinatie van vitrage voor overdag en een dikker gordijn voor 's avonds. In keuken en badkamer horen materialen die tegen vocht en vet kunnen: aluminium jaloezieën, kunststof rolgordijnen of houtlook lamellen van pvc.",
              "Voor een bureau of een kamer met een scherm is een lichtfilterend rolgordijn handig: het neemt de schittering weg zonder de kamer donker te maken."]),
            ("Stof, kleur en patroon",
             ["Een gordijn in dezelfde tint als de muur laat het raam opgaan in de wand en maakt de kamer rustig en groot. Een gordijn in een contrasterende tint maakt het raam een blikvanger. Patronen werken op grote ramen; op een klein raam wordt een patroon snel druk. Linnen en linnenlook ogen natuurlijk en licht, velours is warm en dempt geluid het best."]),
            ("Opmeten en ophangen",
             ["Meet elk raam apart en meet breedte en hoogte op drie plaatsen: boven, midden en onder. Oude ramen zijn zelden haaks. Bevestig een gordijnrail met voldoende steunen, minstens om de 50 centimeter en aan beide uiteinden, want een rail met zware stof hangt anders door. In gipskartonplafonds en -wanden zijn hollewandpluggen of een bevestiging in de staanders nodig, zie het thema over boren en ophangen."]),
            ("Op maat laten maken",
             ["Wie het opmeten en ophangen liever uitbesteedt, kan terecht bij een specialist. Heytens, in België al sinds 1974 actief in raamdecoratie, met een Nederlandstalige site op https://www.heytens.com/be-nl, maakt gordijnen, rolgordijnen en jaloezieën op maat en komt aan huis om te meten en te plaatsen. Voor een decorateur die een volledig project oplevert, is zo'n partij handig omdat maatwerk het verschil maakt bij ongelijke ramen."]),
        ],
        "partner": {"name": "Heytens", "url": "https://www.heytens.com/be-nl", "anchor": "Heytens",
                    "blurb": "Gordijnen, rolgordijnen en jaloezieën op maat, opgemeten en geplaatst aan huis."},
    },
    {
        "slug": "vloeren",
        "nr": "06",
        "title": "Vloeren",
        "h1": "Vloeren: laminaat, vinyl of parket",
        "meta": "Welke vloer past bij welke ruimte en welk gebruik. Over laminaat, vinyl, parket, legrichting, ondervloer en de aansluiting op muren en deuren.",
        "intro": "De vloer is het grootste vlak dat iemand aanraakt. Ze bepaalt het geluid van een kamer, het gevoel onder de voeten en de basistint waar alles op moet passen. Een decorateur kiest de vloer meestal als eerste, nog voor de muurkleur, omdat een vloer tientallen jaren blijft liggen en een muur in een weekend overgeschilderd is.",
        "kort": [
            "Laminaat voor slijtvastheid en eenvoud, vinyl voor vochtige ruimtes en stilte, parket voor echt hout dat te renoveren is.",
            "Leg planken in de richting van het licht, van het raam de kamer in.",
            "Een ondervloer is geen luxe: ze dempt geluid en vangt oneffenheden op.",
            "Houd een uitzettingsvoeg van 8 tot 10 millimeter langs alle muren vrij.",
        ],
        "sections": [
            ("Drie families",
             ["Laminaat is een HDF-plaat met een fotolaag en een slijtvaste toplaag. Het is hard, krasbestendig en eenvoudig te leggen met een kliksysteem. Vinyl, tegenwoordig meestal als klikvinyl in planken of tegels, is soepel, stil en waterbestendig, en daarmee geschikt voor keuken, badkamer en hal. Parket is echt hout: massief of als meerlaags parket met een toplaag van echt hout op een drager. Parket kan geschuurd en opnieuw afgewerkt worden en gaat daardoor het langst mee.",
              "De keuze hangt af van de ruimte en het gebruik. Een gezin met kinderen en een hond kiest vaak laminaat of vinyl in de leefruimte. Wie de warmte van hout wil in een slaap- of woonkamer, kiest parket. In natte ruimtes is vinyl of tegel de logische keuze."]),
            ("Legrichting en formaat",
             ["Planken worden gelegd in de richting van het invallende licht, dus van het grootste raam de kamer in. Zo vallen de naden weg. In een lange, smalle kamer kan dwars leggen de ruimte breder laten lijken, maar dat gaat ten koste van de lichtval. Brede en lange planken maken een kamer ruimer; smalle planken in visgraat maken ze klassieker en drukker.",
              "Een middentint is het veiligst: lichte vloeren tonen elk vuiltje, donkere vloeren elk stofje. Een vloer met wat kleurverschil tussen de planken oogt natuurlijker dan een egale vloer."]),
            ("Ondervloer en voorbereiding",
             ["Een zwevende vloer hoort op een ondervloer. Die dempt loopgeluid, vangt kleine oneffenheden op en houdt bij een betonnen ondergrond vocht tegen met een dampscherm. De ondergrond moet vlak zijn: oneffenheden van meer dan 2 tot 3 millimeter per meter worden eerst geëgaliseerd, anders klapperen de kliksystemen los.",
              "Laat de vloer 48 uur in de kamer acclimatiseren voor het leggen. Houd rondom een uitzettingsvoeg van 8 tot 10 millimeter vrij, ook bij deurkozijnen en verwarmingsbuizen. Die voeg wordt nadien verborgen achter plinten en afdekrozetten."]),
            ("Aansluitingen",
             ["De afwerking maakt het verschil. Plinten in de kleur van de muur laten de vloer groter lijken; plinten in de kleur van de vloer kaderen de kamer af. Deurkozijnen worden onderaan ingezaagd zodat de vloer eronder schuift, wat netter is dan een profiel ertegen. Bij een overgang tussen twee vloeren hoort een laag overgangsprofiel, bij voorkeur in dezelfde tint als de vloer."]),
            ("Een Belgisch merk",
             ["Voor laminaat, vinyl en parket is Quick-Step een van de bekendste namen, een merk uit Wielsbeke in West-Vlaanderen met een Belgische site op https://www.quick-step.be/nl-be. Het aanbod omvat de drie families uit dit artikel, met bijhorende ondervloeren, plinten en profielen die op de vloeren zijn afgestemd, wat het afwerken van aansluitingen eenvoudiger maakt."]),
        ],
        "partner": {"name": "Quick-Step", "url": "https://www.quick-step.be/nl-be", "anchor": "Quick-Step",
                    "blurb": "Laminaat, vinyl en parket met bijhorende ondervloeren, plinten en profielen."},
    },
    {
        "slug": "tegels",
        "nr": "07",
        "title": "Tegels",
        "h1": "Tegels kiezen voor vloer, wand en terras",
        "meta": "Keramische tegels, natuursteen en grootformaat: hoe formaat, voeg en legpatroon een ruimte veranderen. Voor badkamer, keuken, hal en terras.",
        "intro": "Tegels zijn het meest blijvende afwerkingsmateriaal in een woning. Waar verf en textiel na een paar jaar vervangen worden, blijven tegels vaak tientallen jaren liggen. Dat maakt de keuze zwaarder, maar het maakt ook dat een goed gekozen tegel het karakter van een badkamer of hal decennialang draagt.",
        "kort": [
            "Grootformaat tegels met smalle voegen maken een kleine ruimte groter.",
            "Kies voor vloeren een slipvaste tegel; in de badkamer minstens antislipklasse R10.",
            "Voegkleur in de tint van de tegel geeft rust, contrasterende voeg toont het patroon.",
            "Terrastegels van 2 centimeter dik zijn vorstbestendig en op tegeldragers te leggen.",
        ],
        "sections": [
            ("Keramiek of natuursteen",
             ["Keramische tegels, en dan vooral porselein of gres, zijn dicht, hard en nauwelijks poreus. Ze kunnen in vrijwel elke ruimte, ook buiten, en vragen weinig onderhoud. Natuursteen zoals blauwe hardsteen, marmer of travertijn heeft een uniek uiterlijk maar is poreuzer en moet geïmpregneerd worden. In een badkamer met veel kalk is marmer een keuze die onderhoud vraagt; in een hal geeft blauwe hardsteen een tijdloze, Belgische uitstraling."]),
            ("Formaat en voeg",
             ["Grote tegels met smalle voegen geven een rustig vlak en maken een kleine ruimte visueel groter. Kleine tegels met veel voegen maken een ruimte drukker maar ook gezelliger, en ze zijn praktischer op een vloer met afschot naar een doucheput. Een voeg in de tint van de tegel laat het vlak als geheel lezen; een donkere voeg bij een lichte tegel toont het patroon en verbergt vuil.",
              "Legpatronen doen veel: halfsteensverband voor een klassieke muur, visgraat voor een warme vloer, tegels in de lengte gelegd om een gang langer te maken of dwars om hem breder te laten ogen."]),
            ("Vloer, wand en buiten",
             ["Voor vloeren is slipweerstand belangrijk. In een badkamer hoort een tegel met antislipklasse R10 of hoger, in een inloopdouche liever R11. Wandtegels hoeven niet slipvast te zijn en mogen dus glanzend zijn, wat het licht mooi weerkaatst. Buiten worden tegels van 2 centimeter dik gebruikt, die vorstbestendig zijn en los op tegeldragers of in split gelegd kunnen worden, wat het water goed laat afvoeren."]),
            ("Voorbereiding en plaatsing",
             ["Een tegelvloer is zo goed als de ondergrond. Een chape moet droog, vlak en stabiel zijn. In een badkamer wordt de wand en vloer in de douchezone eerst waterdicht gemaakt met een kimband en een afdichtingslaag. Grootformaat tegels worden met dubbele verlijming geplaatst, dus lijm op de vloer en op de tegel, om holtes te vermijden.",
              "Wie een tegel kiest, neemt best een aantal stalen mee naar huis en legt ze op de vloer naast de muurkleur en het sanitair. Een tegel in de toonzaal onder tl-licht oogt anders dan thuis bij daglicht."]),
            ("Toonzalen in de Benelux",
             ["Voor wie tegels in het echt wil zien, is een toonzaal onmisbaar. Impermo, met een webshop op https://www.impermo.be/ en meerdere toonzalen in België, biedt duizenden vloer-, wand- en terrastegels plus lijm, voeg en profielen. Het brede aanbod maakt het mogelijk om binnen- en buitentegels op elkaar af te stemmen, wat voor een doorlopende vloer van woonkamer naar terras belangrijk is."]),
        ],
        "partner": {"name": "Impermo", "url": "https://www.impermo.be/", "anchor": "Impermo",
                    "blurb": "Vloer-, wand- en terrastegels met toonzalen in België en een ruime webshop."},
    },
    {
        "slug": "meubels",
        "nr": "08",
        "title": "Meubels en indeling",
        "h1": "Meubels en indeling: een plattegrond voor het inrichten",
        "meta": "Meubels kiezen en plaatsen op basis van een plattegrond. Over looproutes, maten, zones en de verhouding tussen meubel en kamer.",
        "intro": "Een decorateur begint een inrichting niet bij de winkel maar bij de plattegrond. Hoe een kamer gebruikt wordt, waar het licht vandaan komt en hoe mensen erdoor lopen bepaalt waar de zetel, de tafel en de kasten komen. Pas daarna wordt gekozen welke meubels dat worden.",
        "kort": [
            "Teken de kamer op schaal en schuif met papieren meubels voor er iets gekocht wordt.",
            "Houd looproutes van minstens 80 centimeter vrij, rond een eettafel 90 centimeter.",
            "Een zithoek wordt gedragen door een tapijt en een lage tafel, niet door meubels tegen de muren.",
            "Meubels in dezelfde hoogte en dezelfde materiaalfamilie brengen rust.",
        ],
        "sections": [
            ("Werken met een plattegrond",
             ["Een plattegrond op schaal, met ramen, deuren, radiatoren en stopcontacten erop, is het beste hulpmiddel om een inrichting te plannen. Met uitgeknipte papieren meubels op dezelfde schaal wordt in een kwartier duidelijk of een hoekzetel past, of de eettafel uitgetrokken kan worden en of de kast de deur niet hindert. Dat kwartier bespaart een verkeerde aankoop."]),
            ("Maten en looproutes",
             ["Een paar maten die decorateurs uit het hoofd kennen: een looproute is minstens 80 centimeter breed, rond een eettafel is 90 centimeter nodig om een stoel achteruit te schuiven, tussen zetel en salontafel ligt 40 tot 45 centimeter, en een tv hangt op een afstand van ongeveer twee tot tweeënhalf keer de schermdiagonaal. Een bed heeft aan minstens een zijde 70 centimeter vrije ruimte nodig, liever aan beide zijden."]),
            ("Zones maken",
             ["In een open leefruimte worden zones gemaakt met tapijten, verlichting en de rug van een zetel. Een zetel met de rug naar de keuken maakt een zithoek; een tapijt onder die zithoek versterkt dat. Meubels tegen alle muren zetten maakt de kamer leeg in het midden en de wanden druk. Een zetel die van de muur af staat, met een smalle tafel of een lamp erachter, maakt een kamer juist ruimer."]),
            ("Verhouding en samenhang",
             ["Een groot meubel in een kleine kamer werkt beter dan veel kleine meubels. Een grote zetel, een grote tafel en een kast tot het plafond geven rust; vijf kleine kastjes geven onrust. Meubels in dezelfde hoogte, bijvoorbeeld een dressoir en een bureau op dezelfde hoogte als de vensterbank, vormen een lijn die de kamer ordent. Materialen in een familie, hout bij hout en zwart metaal bij zwart metaal, brengen samenhang zonder dat alles uit dezelfde reeks hoeft te komen."]),
            ("Planningshulpmiddelen en aanbod",
             ["Voor wie de plattegrond liever digitaal maakt, biedt IKEA op https://www.ikea.com/be/nl/ naast meubels ook online planners voor keukens, kasten en woonkamers, waarmee een kamer op maat ingedeeld wordt voor er iets besteld is. Het brede aanbod in vaste maten maakt het bovendien eenvoudig om meubels in dezelfde hoogte en dezelfde materiaalfamilie te combineren."]),
        ],
        "partner": {"name": "IKEA", "url": "https://www.ikea.com/be/nl/", "anchor": "IKEA",
                    "blurb": "Meubels, opbergsystemen en online planners voor keuken, kast en woonkamer."},
    },
    {
        "slug": "keuken-en-tafel",
        "nr": "09",
        "title": "Keuken en tafel",
        "h1": "Keuken en tafel: gebruiksvoorwerpen als decoratie",
        "meta": "Hoe keukengerei, servies en tafellinnen een open keuken aankleden. Over open rekken, materialen die mooi verouderen en de gedekte tafel als decoratie.",
        "intro": "In een woning met een open keuken staat het keukengerei in het zicht. De pannen, de snijplank, de theepot en de stapel borden zijn dan geen gebruiksvoorwerpen meer maar onderdeel van de inrichting. Decorateurs behandelen de keuken daarom als een kamer met dezelfde regels als de woonkamer: een palet, een materiaalfamilie en een paar goede stukken.",
        "kort": [
            "Open rekken tonen alleen wat mooi is; de rest gaat achter deuren.",
            "Kies materialen die mooi verouderen: hout, gietijzer, geëmailleerd staal, aardewerk, linnen.",
            "Beperk het aantal kleuren op het aanrecht tot het palet van de kamer.",
            "Een gedekte tafel is decoratie: servies, glaswerk en linnen in een familie kiezen.",
        ],
        "sections": [
            ("Open of dicht",
             ["Open rekken zijn mooi op foto's en lastig in het dagelijks leven, tenzij er een regel bij hoort: op het rek staat alleen wat mooi is en dagelijks gebruikt wordt. Een stapel borden in een tint, een rij glazen potten met droge voorraad, een paar houten planken. Alles wat kleurrijk, plastic of half leeg is, gaat achter een deur. Zo blijft een open rek een stilleven in plaats van een berging."]),
            ("Materialen die mooi ouder worden",
             ["Een keuken wordt gebruikt en dus beschadigd. Materialen die daar goed op reageren, worden mooier met de jaren: een houten snijplank, een gietijzeren pan, een geëmailleerde ketel, aardewerk, linnen handdoeken. Glanzend kunststof en bedrukt textiel verouderen slecht. Wie het aanrecht rustig wil houden, kiest een materiaalfamilie, bijvoorbeeld hout met zwart metaal, of wit aardewerk met blank hout, en houdt zich daaraan."]),
            ("De tafel als middelpunt",
             ["In een open leefruimte is de eettafel vaak het grootste meubel en het middelpunt van de kamer. Een gedekte tafel is dan de meest zichtbare decoratie in huis. Servies in een rustige tint, glaswerk in een vorm, linnen placemats of een loper en een lage schaal in het midden zijn genoeg. Hoge bloemstukken en veel verschillende patronen maken een tafel druk en hinderen het gesprek.",
              "Servies hoeft niet uit een reeks te komen. Borden in een tint, kommen in een andere tint uit hetzelfde palet en een afwijkend accentstuk werken vaak beter dan een compleet servies van 48 delen."]),
            ("Winkels met een eigen handschrift",
             ["Een winkel die deze aanpak al jaren hanteert, is Dille & Kamille, met een Belgische site op https://www.dille-kamille.be/ en winkels in meerdere Belgische steden. Het aanbod bestaat uit keukengerei, servies, textiel en tuinspullen in natuurlijke materialen zoals hout, linnen, aardewerk en geëmailleerd staal, in een beperkt palet. Voor een decorateur die een keuken wil aankleden zonder kleurenexplosie is dat een praktische bron."]),
        ],
        "partner": {"name": "Dille & Kamille", "url": "https://www.dille-kamille.be/", "anchor": "Dille & Kamille",
                    "blurb": "Keukengerei, servies, textiel en tuinspullen in natuurlijke materialen."},
    },
    {
        "slug": "planten-en-buiten",
        "nr": "10",
        "title": "Planten en buiten",
        "h1": "Planten en buiten: groen als afwerking van een ruimte",
        "meta": "Kamerplanten, potten en het terras als verlengstuk van het interieur. Over lichtbehoefte, plaatsing, potten in het palet en de overgang van binnen naar buiten.",
        "intro": "Een ruimte zonder iets levends erin voelt af maar niet bewoond. Planten brengen beweging, een tint groen die bij elk palet past en een zachtere akoestiek. Decorateurs gebruiken planten daarom als de allerlaatste laag, na de accessoires, en ze kijken daarbij verder dan de vensterbank: het terras en de tuin zijn vanuit een leefruimte met grote ramen evengoed onderdeel van het interieur.",
        "kort": [
            "Kies planten naar het licht dat er is, niet naar de plek waar een plant mooi zou staan.",
            "Een grote plant op de vloer doet meer dan tien kleine op de vensterbank.",
            "Potten in het palet van de kamer, en per kamer een materiaal: terracotta, keramiek of metaal.",
            "Het terras krijgt dezelfde tinten en materialen als de kamer ernaast.",
        ],
        "sections": [
            ("Licht eerst",
             ["De meeste kamerplanten sneuvelen niet door te weinig water maar door te weinig licht. Een plant hoort op een plek die bij zijn lichtbehoefte past. Een raam op het zuiden vraagt planten die volle zon verdragen; een hoek achter in de kamer vraagt schaduwplanten zoals een zamioculcas of een sansevieria. Wie eerst de plek kiest en dan de plant, houdt de plant in leven."]),
            ("Groot boven klein",
             ["Een grote plant op de vloer, een olijfboom in een kuip, een strelitzia of een ficus van twee meter, doet voor een kamer wat een grote zetel doet: hij geeft rust en schaal. Een vensterbank vol kleine plantjes geeft onrust. Een grote plant in een hoek, een middelgrote op een kast en hooguit een kleine op tafel is meestal genoeg."]),
            ("Potten als accessoire",
             ["Een pot is een woonaccessoire en volgt dus het palet. Terracotta past bij warme tinten en landelijke interieurs, geglazuurde keramiek bij strakke en kleurrijke interieurs, zwart of grijs metaal bij industriële ruimtes. Een kamer krijgt een materiaal voor alle potten, geen mengeling. Binnenpotten zonder gat krijgen een binnenpot met gat en een laag kleikorrels onderin, zodat de wortels niet in het water staan."]),
            ("Van binnen naar buiten",
             ["Bij een leefruimte met grote ramen is het terras het verlengstuk van de kamer. Dezelfde tinten en materialen buiten herhalen, een terrastegel die lijkt op de binnenvloer, buitenkussens in het palet van de kamer, potten in hetzelfde materiaal, laat de ruimte tot de tuin doorlopen. Buitenplanten worden gekozen op winterhardheid en op de stand van de zon op het terras, net zoals binnen op het licht."]),
            ("Planten, potten en tuinbenodigdheden",
             ["Voor planten, potten, potgrond en tuinaccessoires is Aveve, met een webshop op https://www.aveve.be/nl en winkels door heel Vlaanderen, een bekende Belgische naam. Het aanbod bestrijkt zowel kamerplanten als terras- en tuinplanten, met bijbehorende potten en grond, wat handig is wanneer binnen en buiten op elkaar afgestemd moeten worden."]),
        ],
        "partner": {"name": "Aveve", "url": "https://www.aveve.be/nl", "anchor": "Aveve",
                    "blurb": "Kamerplanten, tuinplanten, potten, potgrond en tuinbenodigdheden."},
    },
]

OVER = {
    "title": "Over Decorateursgids.be",
    "meta": "Wat Decorateursgids.be is, waarover de gids gaat en hoe de thema's zijn opgebouwd.",
    "paragraphs": [
        "Decorateursgids.be is een onafhankelijke gids over het afwerken en aankleden van een woning. De site behandelt het werk dat een decorateur doet nadat de bouwer en de installateur vertrokken zijn: schilderen, vloeren leggen, ramen aankleden, verlichting en accessoires plaatsen en alles netjes ophangen.",
        "De gids is opgebouwd rond tien thema's. Elk thema bevat een artikel met de vuistregels die in de praktijk gebruikt worden, een korte samenvatting en een verwijzing naar een winkel of merk waar het materiaal uit het artikel te vinden is. Die verwijzingen zijn gekozen op aanbod en bereikbaarheid in België.",
        "De teksten zijn geschreven voor twee groepen lezers: wie zelf een kamer wil afwerken en wie een decorateur inhuurt en wil begrijpen waar die op let. Er staan geen prijzen op deze site, omdat prijzen per project en per periode verschillen en een gids daar niet betrouwbaar over kan zijn.",
        "Vragen of opmerkingen over de inhoud kunnen per e-mail naar info@decorateursgids.be.",
    ],
}


# Blogs van externe auteurs; brontekst staat in blog/<file>.
BLOGS = [
    {"slug": "roomspray-gebruik-geuren-en-tips", "file": "roomspray.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026",
     "mt": "Roomspray: gebruik, geuren, ingrediënten en tips",
     "meta": "Wat roomspray is, hoe het effectief gebruikt wordt, welke geuren er zijn, waar het in huis past en waar op te letten bij duurzame en vegan opties."},
    {"slug": "aannemers-in-nederland", "file": "aannemers.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026",
     "mt": "Aannemers in Nederland: rol, betrouwbaarheid en keuze",
     "meta": "De rol van aannemers in de bouw, het belang van ervaring, soorten bouwprojecten, het bouwteam, duurzaamheid en veelgestelde vragen over aannemers."},
    {"slug": "spiraalkneder-werking-en-voordelen", "file": "spiraalkneder.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026",
     "mt": "Spiraalkneder: werking, kenmerken en voordelen",
     "meta": "Hoe een spiraalkneder werkt, welke capaciteit nodig is, het verschil met een standaard keukenmixer en tips voor onderhoud en reiniging."},
    {"slug": "villas-in-canggu-bali", "file": "canggu.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026",
     "mt": "Villa's in Canggu: luxe wonen en investeren op Bali",
     "meta": "Waarom villa's in Canggu gewild zijn: architectuur, rendement en bezettingsgraad, de wijken Berawa, Batu Bolong en Echo Beach en tips bij de keuze."},
]
